"""Builds ../data.js from the timetables. Tokens per period (9 per day, Mon..Fri):
   -  no class | ?  class, room not stated (lab/yoga/CDC) | T  section's home room | 602 or 107+309  room(s) (IST prefix) | TB106 = TB-106
   Edit a row, run:  python tools/build_data.py"""
import json, re, collections, os
AC_ROOMS = set()   # e.g. {"IST 602","IST 518"}; leave empty if unknown (the app then ignores AC filters)
FB=[0,("09:00","09:50"),("09:50","10:40"),("10:50","11:40"),("11:40","12:30"),("12:30","13:20"),("13:20","14:10"),("14:10","15:00"),("15:10","16:00"),("16:00","16:50")]
FA=[0,("09:00","09:50"),("09:55","10:45"),("10:50","11:40"),("11:45","12:35"),("12:35","13:30"),("13:30","14:20"),("14:25","15:15"),("15:20","16:10"),("16:15","17:05")]
DAYS=["Mon","Tue","Wed","Thu","Fri"]; SEC=[]
def S(n,sem,f,home,rows): SEC.append((n,sem,f,home,[r.strip() for r in rows.strip().split("\n")]))
code=lambda t: "TB-"+t[2:] if t.startswith("TB") else "IST "+t
# ---- 2026-27 odd semester (II, III, IV year) ----
S("II BME","2026-27",FB,"602","""
T T T T - 107+309 107+309 - -
T T T T - TB106 TB106 - -
T T T - - TB106 602 - -
T T T T - - - 107+309 107+309
T T T T - - - 602 602""")
S("II ECE-DS A","2026-27",FB,"416","""
T T T T - 602 602 107+309 107+309
T T T T - 602 - TB106 TB106
T T T T - - TB106 - -
T T T T - 107+309 107+309 - -
T T T T - - - - -""")
S("II ECE-DS B","2026-27",FB,"411","""
- - 107+309 107+309 - T T T T
107+309 107+309 - - - T T T T
401 - - - - T T T T
401 401 TB106 TB106 - T T T T
TB106 - - - - T T T T""")
S("III BME","2026-27",FB,"211","""
625 625 107 107 - T T T T
108 108 625 - - T T T T
- - - - - T T T T
- - - 108 - T T T T
108 - - - - T T T T""")
S("III ECE-A","2026-27",FB,"518","""
T T T T - 625 625 - -
T T T T - - 625 - -
T T T T - - - 108+309 108+309
T T T T - - - - -
T T T T - 108+309 108+309 - -""")
S("III ECE-B","2026-27",FB,"518","""
108+309 108+309 - - - T T T T
625 625 - - - T T T T
625 - - - - T T T T
108+309 108+309 - - - T T T T
- - - - - T T T T""")
S("III ECE-DS","2026-27",FB,"519","""
T T T T - - - - -
T T T T - 107+108 107+108 - -
T T T T - - - 625 625
T T T T - - - - -
T T T T - 625 - 107+108 107+108""")
S("IV ECE-A","2026-27",FB,"225","""
T - T T - - - - -
T T T T - - - - -
T 108 T T - - - - -
T T T T - - - - -
T T T T - - - - -""")
S("IV ECE-B","2026-27",FB,"227","""
T T T T - - - - -
T T T T - - - - -
T T T T - - - - -
T T 108 T - - - - -
T T T - - - - - -""")
# ---- I year sheets (dated 2024-25, different period timings, rooms written in each cell) ----
S("I ECE-A","2024-25",FA,None,"""
602 602 602 602 - ? ? 710 710
602 602 602 602 - 20+21 20+21 20+21 20+21
602 602 602 - - 618 618 108 108
602 602 602 602 - 510 510 201 201
602 602 602 602 - 602 626 626 626""")
S("I ECE-B/EEE","2024-25",FA,None,"""
609 710+520 ? ? - 602 602 602 602
20+21 20+21 20+21 20+21 - 602 602 602 602
710+520 617 510 510 618 - 602 602 602
201 201 626 710 - 602 602 602 602
617 617 - 626 626 626 - 602 602""")
S("I ECE-DS","2024-25",FA,None,"""
710 ? 617 617 - 502 502 502 502
? ? 201 201 - 502 502 502 502
510 510 710 - 617 617 502 502 502
710 510 710 502 502 502 - 502 502
626 626 626 ? - 20+21 20+21 20+21 20+21""")
S("I Biotech-B/BME","2024-25",FA,None,"""
520 ? ? 710+520 - 702 702 702 702
710 710 520 710 - - 702 702 702
20+21 20+21 20+21 20+21 - 702 702 702 702
? ? 710 510+520 - 702 702 702 702
702 702 702 702 702 702 - ? ?""")
mins=lambda t:int(t[:2])*60+int(t[3:]); hm=lambda x:"%02d:%02d"%(x//60,x%60)
slots=[]; used=set()
for n,sem,f,home,rows in SEC:
    assert len(rows)==5,n
    for day,row in zip(DAYS,rows):
        toks=row.split(); assert len(toks)==9,(n,day,row)
        per=collections.defaultdict(list)
        for p,tok in enumerate(toks,1):
            if tok=="-": continue
            rs=[None] if tok=="?" else [code(home)] if tok=="T" else [code(x) for x in tok.split("+")]
            for r in rs: per[r].append((mins(f[p][0]),mins(f[p][1]))); used.add(r) if r else 0
        for r,iv in per.items():
            merged=[]
            for s,e in iv:
                if merged and s-merged[-1][1]<=5: merged[-1][1]=e
                else: merged.append([s,e])
            for s,e in merged: slots.append({"section":n,"day":day,"start":hm(s),"end":hm(e),"room":r})
rooms=[{"id":r,"bld":"TB" if r.startswith("TB") else "IST","floor":int(re.sub(r"\D","",r))//100,
        "lab":r in {"IST 107","IST 108","IST 309","IST 617","IST 618","IST 20","IST 21"},
        "ac":(r in AC_ROOMS) if AC_ROOMS else None,"cap":None} for r in sorted(used)]
data={"open":"09:00","close":"17:05","exclude":[],"sections":[{"name":n,"sem":s} for n,s,*_ in SEC],"rooms":rooms,"slots":slots}
open(os.path.join(os.path.dirname(__file__),"..","data.js"),"w").write(
 "/* Generated by tools/build_data.py from the timetable PDFs. Put section names in `exclude` to hide them (e.g. the 2024-25 first-year sheets). */\n"
 "window.DATA = "+json.dumps(data,separators=(",",":"))+";\nwindow.DATA.slots = window.DATA.slots.filter(s => !window.DATA.exclude.includes(s.section));\n")
# ---- sanity check: two sections in one room at the same time ----
sem={n:s for n,s,*_ in SEC}; by=collections.defaultdict(list)
for s in slots:
    if s["room"]: by[(s["room"],s["day"])].append(s)
def clash(a,b): return a["section"]!=b["section"] and a["start"]<b["end"] and b["start"]<a["end"]
same=[(x,y) for v in by.values() for i,x in enumerate(v) for y in v[i+1:] if clash(x,y) and sem[x["section"]]==sem[y["section"]]]
cross=[(x,y) for v in by.values() for i,x in enumerate(v) for y in v[i+1:] if clash(x,y) and sem[x["section"]]!=sem[y["section"]]]
print(len(SEC),"sections,",len(rooms),"rooms,",len(slots),"slots")
print("clashes inside the same semester:",len(same)); [print("  ",x["room"],x["day"],x["start"],x["section"],"vs",y["section"]) for x,y in same[:8]]
print("2024-25 vs 2026-27 overlaps:",len(cross))
